
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jwt_api_boiler_development

test:
  <<: *default
  database: jwt_api_boiler_test

production:
  <<: *default
  database: jwt_api_boiler_production
  username: jwt_api_boiler
  password: <%= ENV['JWT_API_BOILER_DATABASE_PASSWORD'] %>
